### ISSUE TITLE
User Story #1 Add static list 

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#1]
## Value Proposition

As a User
I want to see a list of my to-dos,
so I can keep track of my tasks.

## Description

![User Story 1(3)](https://user-images.githubusercontent.com/117644039/213735757-62a791a9-6d99-4c46-abc5-deb4f2b3418c.png)

## Acceptance Criteria

- [x] the app's title is fixed to the top of the screen
- [x] a list with all tasks is displayed
- [x] each to-do task from a static json will be displayed as a card

## Tasks

- [x] create a title and fix it to the top of the screen
- [x] create a json file with static data
 - [  ] db.json: 
 ```json
[
  {
   "id": "0",
   "task": "clean the kitchen"
  },
  {
   "id": "1",
   "task": "grocery shopping"
  }
]
```
- [x] create a component to render the tasks

## Complexity

S

**Comment by mbosselmann** [comment]
Hi Michael,
your user story looks great! You rock! 🪨 I have some remarks for you:

**Value proposition**
- I do not now if "kanban list" really exists. As long as you do not implement the kanban board feature I think you could also write:

As a User
I want to see a list of my to-dos,
so I can keep track of my tasks.

**Description**
Your description is cool! But is to-do I or II really everything the user will see? Or would it be better to name the todo like "clean the kitchen" or "answer my colleague"?

**Acceptance criteria**
The criteria are fine, maybe you need to adjust the last criterion to describe what the user will see. For example:
- Every task is displayed in a card
- Each card displays the to-do name

**Tasks**
- if you want to you may add an example data structure for your static data

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by anotherMichaelMaier** [comment]
Hey Mareike,
I added the improvements as you suggested.
I also struggled with the "kanban list" term aswell, since a kanban board goes from left to right and my kanban board should be a list from top to bottom, but I think you recommended the right solution!

Thanks for the review!

**Comment by mbosselmann** [comment]
Hi Michael,
good job! 💪 I have some further remarks. 👼 

**Description**
- I would remove the "e.g." as these are your example tasks, but I think this is not how a user would save the task. The user would write "clean the kitchen" and not "e.g. cleaning the kitchen" or? Therefore, I would remove the "e.g." :)

**Acceptance criteria**
- "- [ ] db.json:" is not formatted correctly and I would write your example data like this:
```js
[
  {
   "id": "0",
   "task": "clean the kitchen"
  },
  {
   "id": "1",
   "task": "grocery shopping"
  }
]
```

- And I would save id values as strings as later when you can create new tasks, you will use a package like uuid to generate unique ids and these ids will also be strings. :)
- "create a component to render the tasks": the part "in the json file" is not needed to describe this task correctly

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by mbosselmann** [comment]
Hi Michael,
LGTM! 🪨 "- [ ] db.json:" is still not formatted correctly, but that does not hinder me to approve your first user story! 💪 

Happy hacking! 🚀
