### ISSUE TITLE
User Story #6 make the done page work

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#10]
## Value Proposition

As a User
I want to see a list of my completed tasks
so that I can keep track what I've done already

## Description

![User Story 6](https://user-images.githubusercontent.com/117644039/215167310-b78d5608-f8a4-41ec-afb7-3d08f82a7043.png)

## Acceptance Criteria

- [ ] The done page is highlighted in the navbar when you're currently on it
- [ ] The dome page is rendering only cards that the User has done already

## Tasks

- [ ] read up about filtering arrays
- [ ] create a filter function
- [ ] add styling component to the navbar

## Complexity

M

**Comment by d-opri** [comment]
my comment for the previous US applies here as well :)

take the time to go through the necessary steps that will bring you from point a to point b before diving into the code
