### ISSUE TITLE
User Story #7 // card buttons

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#11]
## Value Proposition

As a User 
I want to change my tasks from To-Do -> Doing -> Done
so that I can keep track what I still have to do or done already.

## Description

![User Story 7(1)](https://user-images.githubusercontent.com/117644039/215543558-500ffd1e-5bf9-4b7f-87b9-53800ececd0f.png)

## Acceptance Criteria

- [ ] every card on the "To-Do" page should have one button to move the cards to the "Doing" page
- [ ] every card on the "Doing" page should have two buttons to move the cards to the "To-Do" or "Done" page
- [ ] every card on the "Done" page should have one button to move the cards to the  "Doing" page
- [ ] every button should, when clicked, bring the card to the according page
  - [ ] for instance the User clicks the "Doing" button on a card on the "To-Do" page 
         this would make the card disappear on the "To-Do" page and the card will be displayed
         on the "Doing" page now.

## Tasks

- [ ] create a "To-Do" button
- [ ] create a "Doing" button
- [ ] create a "Done" button
- [ ] link the buttons to the "status" key in the object
- [ ] add a onClick to the button
- [ ] the onClick should change the value of the status key

## Complexity

M

**Comment by ghost** [comment]
Well structured US but maybe its bigger than M
