### ISSUE TITLE
User Story #8 edit function

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#12]
## Value Proposition

As a User
I want to be able to edit my to-dos
so that I can edit my data after I created it.

## Description

![User Story 8](https://user-images.githubusercontent.com/117644039/215802625-68c566db-52fb-42ff-912a-98fe507aa6c6.png)

## Acceptance Criteria

- [ ] display a "edit" - button in the details
- [ ] display a save button to save the changes
- [ ] display a cancel button to cancel the changes without submitting

## Tasks

- [ ] create a `useState` to open and close a form
- [ ] create a edit button
  - [ ] this button changes the `useState` of the form what makes the form appear
  - [ ] and the "details page" disappear via another already existing `useState` change
- [ ]  create a cancel button to swap back from the form to the details page without submitting
        the changes.
  - [ ] the button will toggle the `useState`
- [ ] create save button to save the changes and swap back from the form to the details page 
  - [ ] the button will trigger a `onSubmit event` 
  - [ ] the button will toggle the `useState`
  - [ ] changes getting saved in the local storage
  
## Complexity

L

**Comment by JohannesMisch** [comment]
Great user story!

**Comment by Mistake91** [comment]
looks good to me
