### ISSUE TITLE
User Story #9 delete button

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#13]
## Value Proposition

As a user
I want to have a delete button
so that I can delete old to-dos/tasks

## Description

![User Story 9](https://user-images.githubusercontent.com/117644039/215808918-90d3b5c0-d4ee-4292-9d61-acbd4c7f20d7.png)

## Acceptance Criteria

- [ ] a delete button should always be displayed on all cards on the "Done" page
- [ ] a delete button should always be displayed in the edit form (#12 )
- [ ] the delete button should delete the task / to-do

## Tasks

- [ ] create a delete button component
- [ ] add a delete button
  - [ ] the button should handle a onClick which calls a filter function
  - [ ] the filter function should delete the selected to-do / task with the id key

## Complexity

M

**Comment by Mistake91** [comment]
hey michael, looks pretty good for me
