### ISSUE TITLE
User Story #10 estimated time accumulate feature

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#17]
## Value Proposition

As a User I want to see the accumulated time of my tasks on my doing page,
so that I know how much time I'll need to finish my chosen tasks.

## Description

![User Story 10](https://user-images.githubusercontent.com/117644039/216962901-237d23ae-0509-416b-868b-01662eb90b62.png)

## Acceptance Criteria

- [ ] a counter should be shown on the "doing page"
- [ ] the counter should accumulate the estimated time from the details page of each card

## Tasks

- [ ] write a function that accumulate the estimated time from every task showing ob the "doing page"
- [ ] add a container to the "doing page" to showcase the accumulated time

## Complexity

M/L

**Comment by RobinWitt** [comment]
looks good to me
