### ISSUE TITLE
User Story #2 Add-a-task-button

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#2]
## Value Proposition

As a User
I want a button to add new tasks,
so that my To-Do-List grows with my daily tasks.

## Description

![User Story 2(2)](https://user-images.githubusercontent.com/117644039/214081898-3134f591-874d-4197-bc87-79cf8adc5e82.png)

## Acceptance Criteria

- [ ] a button should be shown on the top of the list
- [ ] the button should be clickable
- [ ] the button should then open a form
  - [ ] the form should include three inputs
     - To-Do (task)
     - Notes
     - estimated time to complete
- [ ] the new task should add on top of the existing list

## Tasks

- [ ] create a button
- [ ] make the button clickable
- [ ] create a form
- [ ] add a handleSubmit for the form inputs

## Complexity

M/L

**Comment by mbosselmann** [comment]
Hi Michael,
that is a well defined and small user story! 💪 I have some remarks for you:

**Value proposition**
- your value proposition is missing the third part (the reason):

**As a** ... (User, Author, logged in User...)
**I want to** ... (describe the goal)
**so that** ... (describe the reason)

**Acceptance criteria**
- you should describe the three input elements in your form as acceptance criteria
- and is the plus button also the submit button for your form? Or wouldn't it be better for the user to have a button to toggle the form and an extra button to submit the form? 🤔 
- you can also describe that the new task will be displayed on top or on the bottom of the list

**Tasks**
- your tasks are small and precise, I would add that you need a handleSubmit function for your form to work

I hope this does help. Feel free to ask if you have further questions. :)

**Comment by RobinWitt** [comment]
I see you implemented the changes as suggested, so it looks good to me!
