### ISSUE TITLE
UserStory #11 // lot of css

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#20]
## Value Proposition

**As a** User
**I want to** have a styled app
**so that** the app is visually appealing to me.

## Description
-

## Acceptance Criteria

- [ ] the app should have a appealing styling 
- [ ] the app should still work like intended

## Tasks

- [ ] add most of the styling in a global css
- [ ] check all pages if there is still styling from the beginning that is not needed anymore.
-[ ] add styled-components

## Complexity

M

**Comment by Long-HaHoang** [comment]
Wow, such a masterpiece. Must be the rumored a Piccasso Maier piece. ✅
