### ISSUE TITLE
User Story #3

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#5]
## Value Proposition

As a User,
I want to see where my tasks at (To-Do, Doing, Done),
so I can keep track about my task progress.

## Description

![User Story 2(3)](https://user-images.githubusercontent.com/117644039/214287744-5dc6697d-8ee1-4604-a001-7bcdace67eac.png)

## Acceptance Criteria

- [ ] a nav bar should be sticked to the bottom of the screen with three tabs
- [ ] a "Doing" link should be included in the navbar
- [ ] a "Done" link should be included in the navbar
- [ ] every tab should lead you to the according list

## Tasks

- [ ] add a "Doing" link
- [ ] add a "Done" link
- [ ] add a page for the "Doing" list
- [ ] add a page for the "Done" list
- [ ] add nav bar to navigate through the app

## Complexity

M

**Comment by JohannesMisch** [comment]
Hello Michael, I am not quite sure but I think a button is the wrong choice inside the navbar, I would use a"Link" component.
