### ISSUE TITLE
User Story #4

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#6]
## Value Proposition

As a User
I want to see first a list of all of my tasks before looking into the details
so that I can get an overview.

## Description

![User Story 4(2)](https://user-images.githubusercontent.com/117644039/214872479-221b4a1d-288d-4de3-9154-7cdaad6546a0.png)

## Acceptance Criteria

- [ ] make the cards hide the details
- [ ] make the cards only show the To-Do
- [ ] make a toggle button to show the details

## Tasks

- [ ] create button with onClick
- [ ] create a useState for the toggle function
- [ ] create a ternary operator to show/hide the details

## Complexity

S

**Comment by marcterre** [comment]
Hey Michael, for me its not clear how we can see more details? Do we have to click a button or can we click the card? What did the card display before? Maybe use a wireframe 🙂
In your value proposition you write "I would like to see my task details, so I can see my details.". You mentioned that you would like to see your details twice.. Maybe write something like: "I would like to see the details of my task, so that i have more information about what I need to pay attention to".

**Comment by AstridOttmann** [comment]
Hey :-) looks good, just some small notes: 
your last tasks is the same as your last Acceptance criteria. Maybe you can specify in the tasks what is to do on developer site (write a function ...). 
Another suggestion for your Value Proposal (Am I right that currently the details are shown and you want to hide them?): 
As a User
I want to see first a list of all of my tasks before looking into the details
so that I can get an overview

**Comment by Mistake91** [comment]
hey Michael, for me it looks good now :)

**Comment by AstridOttmann** [comment]
I agree :-)
