### ISSUE TITLE
User Story #5 // make the doing page work 

### ISSUE THREAD

**Issue by anotherMichaelMaier** [anotherMichaelMaier/capstone-project#9]
## Value Proposition

As a User
I want to see my tasks in progress
so that I can keep track of my progress.

## Description

![User Story 5 1](https://user-images.githubusercontent.com/117644039/215267879-5cd8d8f8-db1d-4cef-8ff3-2d9cfa3f4743.png)

## Acceptance Criteria

- [ ] The doing page is highlighted in the navbar when you're currently on it
- [ ] The doing page is rendering only cards that the User is "doing" right now

## Tasks

- [ ] read up about filtering arrays
- [ ] create a filter function
- [ ] add styling component to the navbar

## Complexity

M

**Comment by d-opri** [comment]
morrning, 

this is just a suggestion, but you might want to think of other ways to describe the "doing" tag, could be "active" or "active tasks" maybe. theyre all a bit too similar right next to each other in my opinion.

since the done page is in your next US, you dont need to include the navigation for it in this wireframe, since it wont be functional until then

"read up about filtering arrays" may be correct, but this is the part where you should be more descriptive; you are laying out your game plan after all. once you have a more clear understanding of _what_ you want to do, not just _that_ you want to do it, your next step (coding) will be less frustrating for you. its worth it to spend more time on this, atleast if youre unsure about how to proceed.

**Comment by anotherMichaelMaier** [comment]
> morrning,
> 
> this is just a suggestion, but you might want to think of other ways to describe the "doing" tag, could be "active" or "active tasks" maybe. theyre all a bit too similar right next to each other in my opinion.
> 
Hey Dani, you're right I could change the wording but in the App I have Icon's for the links already, the "To-Do, Doing, Done" are just short placeholders in the wireframe.

> since the done page is in your next US, you dont need to include the navigation for it in this wireframe, since it wont be functional until then

Fixed that.

> "read up about filtering arrays" may be correct, but this is the part where you should be more descriptive; you are laying out your game plan after all. once you have a more clear understanding of _what_ you want to do, not just _that_ you want to do it, your next step (coding) will be less frustrating for you. its worth it to spend more time on this, atleast if youre unsure about how to proceed.

I'm not sure about this point because thats exactly how I understood Felix on Friday when we did the checkout. I understood it's completly fine to take it as a task if you have to look into something because you're not 100% sure anymore how it works. So I'm kinda confused now, maybe you can elaborate how you understood what he said, I would appreciate it.

Thanks for your feedback so far!

**Comment by d-opri** [comment]
i think it depends on how you want to proceed. you wrote a generic US here but you still need to look up how you want to do it, right? so why not do the research now, and then write down what you find, since you will have to do the research anyway (either you do it before writing the US or after). felix is right, you dont need to know all the steps in detail to go in the right direction. the user story is there to help you conceptualize what you want to do, to plan before you start writing code. this is just a suggestion so you can do it differently of course, and i am no expert so take these steps auf eigene Gefahr, but it could go like this: 

- you need a to-do component, and a way to identify which to-dos are "active"

- you need two states for your list; one which has all items, and one for the "active" items only

- you start out with all items as the default state

- then you need a function to handle the change from one state to the other

- a button that will trigger that change

- the change could be a function (the "filtering arrays" part, you could filter by category or what not)

- then you map over the filtered list, and for each item you render a to-do component

again, you _can_ write in your US that you _have to_ look into sth.. or you can _look into sth_ and _then_ write the US. if you need to do the looking part anyway, why not write it down? i was already in feierabend mentally yesterday so i dont remember everything felix said. and ill approve your stories, but i remember you saying you struggled with this, so i thought it might help clear things up °__°. thats also why i went into the channel thread so you dont have to wait all weekend for a green tick 

sorry for hte wall of text, i hope you can do sth with it. 

and dont work all weekend! 🆗
